database:
  # "sqlite" or "sql"
  type: "sqlite"
  # These values are only needed to be set up if the database type is sql
  mysql:
    host: "127.0.0.1"
    port: 3306
    database: database
    username: root
    password: ''

# Whether to be reminded when an update is uploaded
update-remind: true

# How often to remind players that they can claim their daily rewards.
# Set to -1 to disable, in minutes.
reminder-interval: 10

# How many days before a broadcast is called. Ex. (every 10 days)
# Set to 1 for every day, set to 0 for never.
broadcast-difference: 10

time-remaining:
  can-claim: "Finished"
# %h - The number of hours remaining, %m - The number of minutes remaining, %s - The number of seconds remaining
  waiting: "%hh %mm %ss"

gui:

  name: "&#c9e9f6&lDaily Rewards"

# 9,18,27,36,45,54
  size: 9

# Slots start at 0.
  slots:
    # The size of this list is the amount of daily rewards that are put per page.
    daily: [2,3,4,5,6]
    previous_page: 0
    next_page: 8

  items:
# Set to air to remove.
# This fills all the items that aren't put in slots.
    frame:
      name: "&#c9e9f6&lDaily Rewards"
      item: "LIGHT_BLUE_STAINED_GLASS_PANE"
#      model-data: 3324394
# This is the item that shows when the day can't be claimed and hasn't been claimed yet.
    unclaimed:
      name: "&dDay {day}"
      item: "WHITE_TULIP"
      lore:
        - 'Get a daily streak of {day} days'
        - 'to claim this reward!'
        - ''
        - 'Rewards:'
# This is the item that shows when a particular day has been claimed already.
    claimed:
      name: '&dDay {day}'
      item: 'FERN'
      lore:
        - 'You have claimed the reward'
        - 'for day {day}!'
        - ''
        - 'Rewards:'
# This is the item that shows up when this day is in line for the next claim but hasn't reached the 24-hour cooldown yet.
    unclaimable:
      name: '&dDay {day}'
      item: 'OXEYE_DAISY'
      lore:
        - 'Come back in {time} to'
        - 'claim this reward!'
        - ''
        - 'Rewards:'
# This is the item that shows up when the day can be claimed and hasn't been claimed yet.
    claimable:
      name: '&dDay {day}'
      item: 'OXEYE_DAISY'
      lore:
        - 'Click me to claim'
        - 'your rewards!'
        - ''
        - 'Rewards:'
# This is the item that shows up when a next page is available
    next_page:
      name: "&6Next Page"
      item: "ARROW"
    previous_page:
      name: "&6Previous Page"
      item: "ARROW"

# This is to check if the plugin has been updated but the file hasn't
# Please do not modify this!
file-version: 2